name: Test installers
on:
  pull_request:
  workflow_dispatch:

jobs:
  test-installers:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - "centos:8"
          - "fedora:34"
          - "debian:bullseye"
          - "ubuntu:focal"
          - "ubuntu:hirsute"
        type: [ live, pre-release, release ]
        version: ['1.10', '2.8', '2']
        exclude:
          - type: "release"
            version: "2"
          - type: "live"
            version: "2"
          - type: "pre-release"
            version: "1.10"
          - type: "pre-release"
            version: "2.8"

    env:
      INSTALLER: installer.sh

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python environment
      uses: actions/setup-python@v2

    - name: Setup Python requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Installer
      run: ./mkinstaller.py ${{ matrix.type }} ${{ matrix.version }}

    - name: Workaround for Centos 8
      if: matrix.image == 'centos:8'
      run: |
        cat > installer_centos_8.sh << EOL
        #!/usr/bin/env bash
        find /etc/yum.repos.d/ -type f -exec sed -i 's/mirrorlist=/#mirrorlist=/g' {} +
        find /etc/yum.repos.d/ -type f -exec sed -i 's/#baseurl=/baseurl=/g' {} +
        find /etc/yum.repos.d/ -type f -exec sed -i 's/mirror.centos.org/vault.centos.org/g' {} +
        source /app/installer.sh
        EOL
        chmod +x installer_centos_8.sh
        echo "INSTALLER=installer_centos_8.sh" >> $GITHUB_ENV

    - name: Set up Tarantool in docker
      run: docker run --rm -v $(pwd):/app -e FORCE_INSTALL_TARANTOOL=True ${{ matrix.image }} sh -c "bash /app/${{ env.INSTALLER }}; tarantool --version"
